"""
Code Generator

Generates runnable Python code from the project model.
"""

import os
from typing import Optional

from models import ProjectModel, SceneModel, SpriteModel


class CodeGenerator:
    """Generates Python code from project models."""

    def __init__(self, project: ProjectModel, project_dir: str):
        self.project = project
        self.project_dir = project_dir

    def generate_main(self) -> str:
        """Generate the main game script."""
        game = self.project.game
        scenes = self.project.scenes

        # Build imports
        code = [
            '"""Generated by Scrawl IDE."""',
            '',
            'import sys',
            'import os',
            '',
            '# Add project directory to path',
            f'sys.path.insert(0, r"{self.project_dir}")',
            '',
            'from scrawl import *',
            '',
        ]

        # Generate sprite classes
        for scene in scenes:
            for sprite in scene.sprites:
                code.append(self._generate_sprite_class(sprite))
                code.append('')

        # Generate scene setup
        code.append('')
        code.append('def setup():')
        code.append('    """Set up the game."""')

        if scenes:
            scene = scenes[0]
            bg_color = scene.background_color
            code.append(f'    set_background_color({bg_color[0]}, {bg_color[1]}, {bg_color[2]})')
            code.append('')

            for sprite in scene.sprites:
                code.append(self._generate_sprite_creation(sprite))

        code.append('')
        code.append('')

        # Main execution
        code.append('if __name__ == "__main__":')
        code.append(f'    game = Game({game.width}, {game.height}, "{game.title}")')
        code.append(f'    game.fps = {game.fps}')
        code.append('    setup()')
        code.append('    game.run()')
        code.append('')

        return '\n'.join(code)

    def _generate_sprite_class(self, sprite: SpriteModel) -> str:
        """Generate a sprite class definition."""
        lines = []
        lines.append(f'class {sprite.class_name}(Sprite):')
        lines.append(f'    """Sprite: {sprite.name}"""')
        lines.append('')
        lines.append('    def __init__(self):')
        lines.append('        super().__init__()')

        # Set costumes
        if sprite.costumes:
            for costume in sprite.costumes:
                # Make path relative to project
                rel_path = os.path.relpath(costume, self.project_dir)
                rel_path = rel_path.replace('\\', '/')
                lines.append(f'        self.add_costume(r"{rel_path}")')

        lines.append('')
        lines.append('    def on_start(self):')
        lines.append('        """Called when the game starts."""')
        lines.append('        pass')
        lines.append('')
        lines.append('    def on_update(self):')
        lines.append('        """Called every frame."""')
        lines.append('        pass')

        # Include user script if available
        if sprite.script_path and os.path.exists(sprite.script_path):
            lines.append('')
            lines.append('    # --- User Script ---')
            try:
                with open(sprite.script_path, 'r', encoding='utf-8') as f:
                    script_content = f.read()
                # Indent the script content
                for line in script_content.split('\n'):
                    if line.strip():
                        lines.append(f'    # {line}')
            except IOError:
                pass

        return '\n'.join(lines)

    def _generate_sprite_creation(self, sprite: SpriteModel) -> str:
        """Generate sprite instantiation code."""
        lines = []
        var_name = sprite.name.lower().replace(' ', '_')

        lines.append(f'    {var_name} = {sprite.class_name}()')
        lines.append(f'    {var_name}.go_to({sprite.x}, {sprite.y})')
        lines.append(f'    {var_name}.point_in_direction({sprite.direction})')

        if sprite.size != 1.0:
            lines.append(f'    {var_name}.set_size({sprite.size})')

        if not sprite.visible:
            lines.append(f'    {var_name}.hide()')

        return '\n'.join(lines)

    def generate_sprite_template(self, sprite_name: str) -> str:
        """Generate a template script for a sprite."""
        class_name = sprite_name.replace(' ', '')

        return f'''"""
Sprite script for {sprite_name}.
"""

from scrawl import *


class {class_name}(Sprite):
    """Custom sprite class."""

    def __init__(self):
        super().__init__()
        # Add your costumes here
        # self.add_costume("path/to/image.png")

    def on_start(self):
        """Called when the game starts."""
        pass

    def on_update(self):
        """Called every frame."""
        pass

    def on_key_pressed(self, key):
        """Called when a key is pressed."""
        pass

    def on_clicked(self):
        """Called when the sprite is clicked."""
        pass
'''

    def generate_scene_template(self, scene_name: str) -> str:
        """Generate a template script for a scene."""
        return f'''"""
Scene script for {scene_name}.
"""

from scrawl import *


def setup_{scene_name.lower().replace(' ', '_')}():
    """Set up the scene."""
    # Set background color
    set_background_color(100, 150, 200)

    # Create sprites
    # player = PlayerSprite()
    # player.go_to(400, 300)

    pass
'''

    def save_generated_code(self, output_path: str) -> str:
        """Save the generated code to a file."""
        code = self.generate_main()

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(code)

        return output_path
